package com.entity;

// Generated 2018-5-15 13:42:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer empno;
	private String ename;
	private String job;
	private Integer mrg;
	private Date hiredate;
	private Double sal;
	private Double comm;
	private Byte deptno;

	public Emp() {
	}

	public Emp(String ename, String job, Integer mrg, Date hiredate,
			Double sal, Double comm, Byte deptno) {
		this.ename = ename;
		this.job = job;
		this.mrg = mrg;
		this.hiredate = hiredate;
		this.sal = sal;
		this.comm = comm;
		this.deptno = deptno;
	}

	public Integer getEmpno() {
		return this.empno;
	}

	public void setEmpno(Integer empno) {
		this.empno = empno;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Integer getMrg() {
		return this.mrg;
	}

	public void setMrg(Integer mrg) {
		this.mrg = mrg;
	}

	public Date getHiredate() {
		return this.hiredate;
	}

	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	public Double getSal() {
		return this.sal;
	}

	public void setSal(Double sal) {
		this.sal = sal;
	}

	public Double getComm() {
		return this.comm;
	}

	public void setComm(Double comm) {
		this.comm = comm;
	}

	public Byte getDeptno() {
		return this.deptno;
	}

	public void setDeptno(Byte deptno) {
		this.deptno = deptno;
	}

}
