package com.entity;

// Generated 2018-5-15 15:31:35 by Hibernate Tools 3.4.0.CR1

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer sid;
	private String sname;
	
	// 表示1个学生属于1个班级
	private Stuclass stuclass;
	
	public Stuclass getStuclass() {
		return stuclass;
	}

	public void setStuclass(Stuclass stuclass) {
		this.stuclass = stuclass;
	}

	public Student() {
	}

	public Student(String sname) {
		this.sname = sname;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

}
