package com.entity;

import java.util.List;

// Generated 2018-5-18 10:54:31 by Hibernate Tools 3.4.0.CR1

/**
 * Pet generated by hbm2java
 */
public class Pet implements java.io.Serializable {

	private Integer id;
	private String pname;
	private String color;
	private Integer age;
	private Integer bloodtype;
	private Character sex;
	private String catagory;
	
	// added
	private List bts;
	private Integer beginAge;
	private Integer endAge;

	public Pet() {
	}

	public Pet(String pname, String color, Integer age, Integer bloodtype,
			Character sex, String catagory) {
		this.pname = pname;
		this.color = color;
		this.age = age;
		this.bloodtype = bloodtype;
		this.sex = sex;
		this.catagory = catagory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Integer getBloodtype() {
		return this.bloodtype;
	}

	public void setBloodtype(Integer bloodtype) {
		this.bloodtype = bloodtype;
	}

	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	public String getCatagory() {
		return this.catagory;
	}

	public void setCatagory(String catagory) {
		this.catagory = catagory;
	}

	public List getBts() {
		return bts;
	}

	public void setBts(List bts) {
		this.bts = bts;
	}

	public Integer getBeginAge() {
		return beginAge;
	}

	public void setBeginAge(Integer beginAge) {
		this.beginAge = beginAge;
	}

	public Integer getEndAge() {
		return endAge;
	}

	public void setEndAge(Integer endAge) {
		this.endAge = endAge;
	}

	
}
